name: CI
on: 
  push:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'       
          tidy-checks: ''     
      
      - name: Stop on Failure
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1

  build:
    runs-on: ubuntu-latest
    needs: linter
    env:
      DEPS: "libxml2 make"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies from array
        run: |
          pkgs=($DEPS)
          echo "Install packages: ${pkgs[*]}"
          sudo apt-get update
          sudo apt-get install -y "${pkgs[@]}"
      
      - name: Build
        run: make
      